version: "3.8"

services:
  postgres:
    image: postgres:18
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=eelaa
      - POSTGRES_USER=eelaa
      - POSTGRES_PASSWORD=eelaa
